name: hamster-snap # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: git
adopt-info: hamster # look for parse-info in the hamster part
# summary: Hamster time tracker snap # 79 char long summary
# description: |
#   Hamster is time tracking for individuals. It helps you to keep track of how much time you have spent during the day on activities you choose to track.

architectures: [amd64]

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

layout:
  /usr/share/hamster:
    bind: $SNAP/usr/share/hamster
  /usr/lib/hamster:
    bind: $SNAP/usr/lib/hamster
  /usr/lib/python3/dist-packages:
    bind: $SNAP/usr/lib/python3/dist-packages

slots:
  dbus-service:
    interface: dbus
    bus: session
    name: org.gnome.Hamster
  dbus-gui-service:
    interface: dbus
    bus: session
    name: org.gnome.Hamster.GUI
  dbus-windows-service:
    interface: dbus
    bus: session
    name: org.gnome.Hamster.WindowServer

parts:
  hamster:
    stage-packages:
      - gettext
      - intltool
      - python3-distutils-extra
      - python3-gi
      - python3-gi-cairo
      - python3-distutils
      - python3-dbus
      - python3-xdg
      - gconf2
      - gir1.2-gconf-2.0
      - dconf-cli
    source: https://github.com/projecthamster/hamster.git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    plugin: waf
    parse-info: [usr/share/metainfo/org.gnome.Hamster.GUI.metainfo.xml]

  launcher:
    after: [hamster]
    plugin: dump
    source: snap/local
    organize:
      launcher.py: usr/bin/launcher
      hamster.desktop: usr/share/applications/launcher.desktop

apps:
  hamster-snap:
    common-id: org.gnome.Hamster.GUI
    command: usr/bin/launcher
    extensions: [gnome-3-28]
    desktop: usr/share/applications/launcher.desktop
    plugs:
      - gsettings
      - home
      - system-observe
    slots:
      - dbus-service
      - dbus-gui-service
      - dbus-windows-service
